language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
install: true
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  email: true